<?php

namespace Daniloromka\EAV\Migration;

use Daniloromka\EAV\PDO;

class Setup
{
    public function __construct()
    {
        $pdo = new PDO();

        $sql = 'CREATE TABLE eavjsonb_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category_id INT NOT NULL, attribute_values JSONB DEFAULT NULL, PRIMARY KEY(id));';
        $sql .= 'CREATE TABLE eavjsonb_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));';
        $sql .= 'CREATE TABLE eavjsonb_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));';
        $sql .= 'CREATE TABLE eavjsonb_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, attribute_id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));';
        $sql .= 'CREATE TABLE eavjsonb_category_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, attribute_id INT NOT NULL, category_id INT NOT NULL, is_diapason BOOLEAN NOT NULL, PRIMARY KEY(id));';

        $pdo->exec($sql);
    }
}
